language: go

services:
  - docker

install:
  - echo "install"
  - pwd

script:
  - echo "script"
  - pwd
  - go version
  - chmod +x ./bin/run-test.sh
  - ./bin/run-test.sh

after_success:
  - ssh-keygen -t rsa
  - ssh-copy-id root@139.199.103.169
  - chmod 700 ~/.ssh/   #还是Linux文件权限问题
  - ssh root@139.199.103.169 -o StrictHostKeyChecking=no " cd /root/go/src/github.com/backend && git pull && chmod +x ./deploy.sh && ./deploy.sh"

addons:
  ssh_known_hosts: 139.199.103.169