language: go
services:
- docker
install:
- echo "install"
- pwd
script:
- echo "script"
- pwd
- go version
- chmod +x ./bin/run-test.sh
- echo ${TRAVIS_COMMIT_MESSAGE}
- "./bin/run-test.sh ${TRAVIS_COMMIT_MESSAGE}"
after_success:
- ssh root@139.199.103.169 -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa " cd /root/go/src/github.com/backend
  && git reset --hard && git pull origin test --force && chmod +x ./deploy.sh && ./deploy.sh"
addons:
  ssh_known_hosts: 139.199.103.169
before_install:
- openssl aes-256-cbc -K $encrypted_19a91ac8262c_key -iv $encrypted_19a91ac8262c_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
