// Code generated by protoc-gen-go. DO NOT EDIT.
// source: im-entities.proto

package im_entities

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterRequest struct {
	Username             *string  `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password             *string  `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Email                *string  `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3017226e81765a8, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

type RegisterResponse struct {
	Code                 *string  `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Message              *string  `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3017226e81765a8, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *RegisterResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type User struct {
	Userid               *string  `protobuf:"bytes,1,opt,name=userid" json:"userid,omitempty"`
	Username             *string  `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Email                *string  `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3017226e81765a8, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

type LoginRequest struct {
	Email                *string  `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password             *string  `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3017226e81765a8, []int{3}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type LoginResponse struct {
	Code                 *string  `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Message              *string  `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	User                 *User    `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3017226e81765a8, []int{4}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *LoginResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *LoginResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type Chat struct {
	Chatid               *string  `protobuf:"bytes,1,opt,name=chatid" json:"chatid,omitempty"`
	Userid               *string  `protobuf:"bytes,2,opt,name=userid" json:"userid,omitempty"`
	Chatname             *string  `protobuf:"bytes,3,opt,name=chatname" json:"chatname,omitempty"`
	LastUpdateTime       *string  `protobuf:"bytes,4,opt,name=last_update_time,json=lastUpdateTime" json:"last_update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chat) Reset()         { *m = Chat{} }
func (m *Chat) String() string { return proto.CompactTextString(m) }
func (*Chat) ProtoMessage()    {}
func (*Chat) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3017226e81765a8, []int{5}
}

func (m *Chat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chat.Unmarshal(m, b)
}
func (m *Chat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chat.Marshal(b, m, deterministic)
}
func (m *Chat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chat.Merge(m, src)
}
func (m *Chat) XXX_Size() int {
	return xxx_messageInfo_Chat.Size(m)
}
func (m *Chat) XXX_DiscardUnknown() {
	xxx_messageInfo_Chat.DiscardUnknown(m)
}

var xxx_messageInfo_Chat proto.InternalMessageInfo

func (m *Chat) GetChatid() string {
	if m != nil && m.Chatid != nil {
		return *m.Chatid
	}
	return ""
}

func (m *Chat) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *Chat) GetChatname() string {
	if m != nil && m.Chatname != nil {
		return *m.Chatname
	}
	return ""
}

func (m *Chat) GetLastUpdateTime() string {
	if m != nil && m.LastUpdateTime != nil {
		return *m.LastUpdateTime
	}
	return ""
}

type GetChatListRequest struct {
	Userid               *string  `protobuf:"bytes,1,opt,name=userid" json:"userid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChatListRequest) Reset()         { *m = GetChatListRequest{} }
func (m *GetChatListRequest) String() string { return proto.CompactTextString(m) }
func (*GetChatListRequest) ProtoMessage()    {}
func (*GetChatListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3017226e81765a8, []int{6}
}

func (m *GetChatListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChatListRequest.Unmarshal(m, b)
}
func (m *GetChatListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChatListRequest.Marshal(b, m, deterministic)
}
func (m *GetChatListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChatListRequest.Merge(m, src)
}
func (m *GetChatListRequest) XXX_Size() int {
	return xxx_messageInfo_GetChatListRequest.Size(m)
}
func (m *GetChatListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChatListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetChatListRequest proto.InternalMessageInfo

func (m *GetChatListRequest) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

type GetChatListResponse struct {
	Code                 *string  `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Message              *string  `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Chat                 []*Chat  `protobuf:"bytes,3,rep,name=chat" json:"chat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChatListResponse) Reset()         { *m = GetChatListResponse{} }
func (m *GetChatListResponse) String() string { return proto.CompactTextString(m) }
func (*GetChatListResponse) ProtoMessage()    {}
func (*GetChatListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3017226e81765a8, []int{7}
}

func (m *GetChatListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChatListResponse.Unmarshal(m, b)
}
func (m *GetChatListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChatListResponse.Marshal(b, m, deterministic)
}
func (m *GetChatListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChatListResponse.Merge(m, src)
}
func (m *GetChatListResponse) XXX_Size() int {
	return xxx_messageInfo_GetChatListResponse.Size(m)
}
func (m *GetChatListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChatListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetChatListResponse proto.InternalMessageInfo

func (m *GetChatListResponse) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *GetChatListResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *GetChatListResponse) GetChat() []*Chat {
	if m != nil {
		return m.Chat
	}
	return nil
}

type GetContactListRequest struct {
	Userid               *string  `protobuf:"bytes,1,opt,name=userid" json:"userid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContactListRequest) Reset()         { *m = GetContactListRequest{} }
func (m *GetContactListRequest) String() string { return proto.CompactTextString(m) }
func (*GetContactListRequest) ProtoMessage()    {}
func (*GetContactListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3017226e81765a8, []int{8}
}

func (m *GetContactListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContactListRequest.Unmarshal(m, b)
}
func (m *GetContactListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContactListRequest.Marshal(b, m, deterministic)
}
func (m *GetContactListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContactListRequest.Merge(m, src)
}
func (m *GetContactListRequest) XXX_Size() int {
	return xxx_messageInfo_GetContactListRequest.Size(m)
}
func (m *GetContactListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContactListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContactListRequest proto.InternalMessageInfo

func (m *GetContactListRequest) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

type GetContactListResponse struct {
	Code                 *string  `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Message              *string  `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	User                 []*User  `protobuf:"bytes,3,rep,name=user" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContactListResponse) Reset()         { *m = GetContactListResponse{} }
func (m *GetContactListResponse) String() string { return proto.CompactTextString(m) }
func (*GetContactListResponse) ProtoMessage()    {}
func (*GetContactListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3017226e81765a8, []int{9}
}

func (m *GetContactListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContactListResponse.Unmarshal(m, b)
}
func (m *GetContactListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContactListResponse.Marshal(b, m, deterministic)
}
func (m *GetContactListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContactListResponse.Merge(m, src)
}
func (m *GetContactListResponse) XXX_Size() int {
	return xxx_messageInfo_GetContactListResponse.Size(m)
}
func (m *GetContactListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContactListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetContactListResponse proto.InternalMessageInfo

func (m *GetContactListResponse) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *GetContactListResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *GetContactListResponse) GetUser() []*User {
	if m != nil {
		return m.User
	}
	return nil
}

type SendMessageRequest struct {
	Senderid             *string  `protobuf:"bytes,1,opt,name=senderid" json:"senderid,omitempty"`
	Chatid               *string  `protobuf:"bytes,2,opt,name=chatid" json:"chatid,omitempty"`
	Message              *string  `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageRequest) Reset()         { *m = SendMessageRequest{} }
func (m *SendMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessageRequest) ProtoMessage()    {}
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3017226e81765a8, []int{10}
}

func (m *SendMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageRequest.Unmarshal(m, b)
}
func (m *SendMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageRequest.Marshal(b, m, deterministic)
}
func (m *SendMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageRequest.Merge(m, src)
}
func (m *SendMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessageRequest.Size(m)
}
func (m *SendMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageRequest proto.InternalMessageInfo

func (m *SendMessageRequest) GetSenderid() string {
	if m != nil && m.Senderid != nil {
		return *m.Senderid
	}
	return ""
}

func (m *SendMessageRequest) GetChatid() string {
	if m != nil && m.Chatid != nil {
		return *m.Chatid
	}
	return ""
}

func (m *SendMessageRequest) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type SendMessageResponse struct {
	Code                 *string  `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageResponse) Reset()         { *m = SendMessageResponse{} }
func (m *SendMessageResponse) String() string { return proto.CompactTextString(m) }
func (*SendMessageResponse) ProtoMessage()    {}
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3017226e81765a8, []int{11}
}

func (m *SendMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageResponse.Unmarshal(m, b)
}
func (m *SendMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageResponse.Marshal(b, m, deterministic)
}
func (m *SendMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageResponse.Merge(m, src)
}
func (m *SendMessageResponse) XXX_Size() int {
	return xxx_messageInfo_SendMessageResponse.Size(m)
}
func (m *SendMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageResponse proto.InternalMessageInfo

func (m *SendMessageResponse) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

type CreateChatRequest struct {
	Userid               *string  `protobuf:"bytes,1,opt,name=userid" json:"userid,omitempty"`
	Receiverid           *string  `protobuf:"bytes,2,opt,name=receiverid" json:"receiverid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateChatRequest) Reset()         { *m = CreateChatRequest{} }
func (m *CreateChatRequest) String() string { return proto.CompactTextString(m) }
func (*CreateChatRequest) ProtoMessage()    {}
func (*CreateChatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3017226e81765a8, []int{12}
}

func (m *CreateChatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateChatRequest.Unmarshal(m, b)
}
func (m *CreateChatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateChatRequest.Marshal(b, m, deterministic)
}
func (m *CreateChatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateChatRequest.Merge(m, src)
}
func (m *CreateChatRequest) XXX_Size() int {
	return xxx_messageInfo_CreateChatRequest.Size(m)
}
func (m *CreateChatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateChatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateChatRequest proto.InternalMessageInfo

func (m *CreateChatRequest) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *CreateChatRequest) GetReceiverid() string {
	if m != nil && m.Receiverid != nil {
		return *m.Receiverid
	}
	return ""
}

type CreateChatResponse struct {
	Code                 *string  `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Message              *string  `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Chat                 *Chat    `protobuf:"bytes,3,opt,name=chat" json:"chat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateChatResponse) Reset()         { *m = CreateChatResponse{} }
func (m *CreateChatResponse) String() string { return proto.CompactTextString(m) }
func (*CreateChatResponse) ProtoMessage()    {}
func (*CreateChatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3017226e81765a8, []int{13}
}

func (m *CreateChatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateChatResponse.Unmarshal(m, b)
}
func (m *CreateChatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateChatResponse.Marshal(b, m, deterministic)
}
func (m *CreateChatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateChatResponse.Merge(m, src)
}
func (m *CreateChatResponse) XXX_Size() int {
	return xxx_messageInfo_CreateChatResponse.Size(m)
}
func (m *CreateChatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateChatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateChatResponse proto.InternalMessageInfo

func (m *CreateChatResponse) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *CreateChatResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *CreateChatResponse) GetChat() *Chat {
	if m != nil {
		return m.Chat
	}
	return nil
}

type AddContactRequest struct {
	Userid               *string  `protobuf:"bytes,1,opt,name=userid" json:"userid,omitempty"`
	Receiverid           *string  `protobuf:"bytes,2,opt,name=receiverid" json:"receiverid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddContactRequest) Reset()         { *m = AddContactRequest{} }
func (m *AddContactRequest) String() string { return proto.CompactTextString(m) }
func (*AddContactRequest) ProtoMessage()    {}
func (*AddContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3017226e81765a8, []int{14}
}

func (m *AddContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddContactRequest.Unmarshal(m, b)
}
func (m *AddContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddContactRequest.Marshal(b, m, deterministic)
}
func (m *AddContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddContactRequest.Merge(m, src)
}
func (m *AddContactRequest) XXX_Size() int {
	return xxx_messageInfo_AddContactRequest.Size(m)
}
func (m *AddContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddContactRequest proto.InternalMessageInfo

func (m *AddContactRequest) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *AddContactRequest) GetReceiverid() string {
	if m != nil && m.Receiverid != nil {
		return *m.Receiverid
	}
	return ""
}

type AddContactResponse struct {
	Code                 *string  `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Message              *string  `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddContactResponse) Reset()         { *m = AddContactResponse{} }
func (m *AddContactResponse) String() string { return proto.CompactTextString(m) }
func (*AddContactResponse) ProtoMessage()    {}
func (*AddContactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3017226e81765a8, []int{15}
}

func (m *AddContactResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddContactResponse.Unmarshal(m, b)
}
func (m *AddContactResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddContactResponse.Marshal(b, m, deterministic)
}
func (m *AddContactResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddContactResponse.Merge(m, src)
}
func (m *AddContactResponse) XXX_Size() int {
	return xxx_messageInfo_AddContactResponse.Size(m)
}
func (m *AddContactResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddContactResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddContactResponse proto.InternalMessageInfo

func (m *AddContactResponse) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *AddContactResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "RegisterResponse")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "LoginResponse")
	proto.RegisterType((*Chat)(nil), "Chat")
	proto.RegisterType((*GetChatListRequest)(nil), "GetChatListRequest")
	proto.RegisterType((*GetChatListResponse)(nil), "GetChatListResponse")
	proto.RegisterType((*GetContactListRequest)(nil), "GetContactListRequest")
	proto.RegisterType((*GetContactListResponse)(nil), "GetContactListResponse")
	proto.RegisterType((*SendMessageRequest)(nil), "SendMessageRequest")
	proto.RegisterType((*SendMessageResponse)(nil), "SendMessageResponse")
	proto.RegisterType((*CreateChatRequest)(nil), "CreateChatRequest")
	proto.RegisterType((*CreateChatResponse)(nil), "CreateChatResponse")
	proto.RegisterType((*AddContactRequest)(nil), "AddContactRequest")
	proto.RegisterType((*AddContactResponse)(nil), "AddContactResponse")
}

func init() { proto.RegisterFile("im-entities.proto", fileDescriptor_b3017226e81765a8) }

var fileDescriptor_b3017226e81765a8 = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x49, 0x6f, 0x1a, 0x31,
	0x14, 0xd6, 0x2c, 0x74, 0x79, 0xdd, 0xc0, 0xb4, 0x68, 0xda, 0x43, 0x85, 0x7c, 0xa2, 0x52, 0x4b,
	0xa5, 0xfc, 0x82, 0x24, 0x1c, 0x72, 0x80, 0x48, 0xd1, 0x24, 0x48, 0xb9, 0x24, 0xc8, 0x19, 0x3f,
	0x81, 0x25, 0x66, 0xc9, 0xd8, 0x24, 0x97, 0xfc, 0xf8, 0xc8, 0x9e, 0x05, 0xcf, 0x48, 0xa0, 0x08,
	0x6e, 0x7c, 0xcf, 0x6f, 0x3e, 0x7f, 0x8b, 0x81, 0x9e, 0x88, 0xff, 0x61, 0xa2, 0x84, 0x12, 0x28,
	0xc7, 0x59, 0x9e, 0xaa, 0x94, 0x2e, 0xe0, 0x5b, 0x88, 0x4b, 0x21, 0x15, 0xe6, 0x21, 0x3e, 0x6e,
	0x50, 0x2a, 0xf2, 0x0b, 0x3e, 0x6c, 0x24, 0xe6, 0x09, 0x8b, 0x31, 0x70, 0x86, 0xce, 0xe8, 0x63,
	0x58, 0x63, 0x7d, 0x96, 0x31, 0x29, 0x9f, 0xd3, 0x9c, 0x07, 0x6e, 0x71, 0x56, 0x61, 0xf2, 0x1d,
	0x3a, 0x18, 0x33, 0xb1, 0x0e, 0x3c, 0x73, 0x50, 0x00, 0x7a, 0x0a, 0xdd, 0xed, 0x05, 0x32, 0x4b,
	0x13, 0x89, 0x84, 0x80, 0x1f, 0xa5, 0xbc, 0x62, 0x37, 0xbf, 0x49, 0x00, 0xef, 0x63, 0x94, 0x92,
	0x2d, 0xb1, 0x24, 0xae, 0x20, 0xbd, 0x02, 0x7f, 0x2e, 0x31, 0x27, 0x03, 0x78, 0xa7, 0x75, 0x08,
	0x5e, 0x7e, 0x57, 0xa2, 0x86, 0x5e, 0xb7, 0xa5, 0x77, 0x97, 0xa6, 0xcf, 0xb3, 0x74, 0x29, 0x92,
	0xca, 0x71, 0xbd, 0xe5, 0x58, 0x5b, 0xfb, 0xbc, 0xd2, 0x5b, 0xf8, 0x52, 0x32, 0x1c, 0x62, 0x89,
	0xfc, 0x04, 0x5f, 0x4b, 0x34, 0xaa, 0x3e, 0x9d, 0x74, 0xc6, 0xda, 0x5f, 0x68, 0x46, 0xf4, 0x05,
	0xfc, 0xc9, 0x8a, 0x29, 0xed, 0x36, 0x5a, 0x31, 0xb5, 0x75, 0x5b, 0x20, 0x2b, 0x05, 0xb7, 0x9d,
	0x82, 0xde, 0x30, 0x29, 0x14, 0x66, 0x6b, 0x4c, 0x46, 0xd0, 0x5d, 0x33, 0xa9, 0x16, 0x9b, 0x8c,
	0x33, 0x85, 0x0b, 0x25, 0x62, 0x0c, 0x7c, 0xb3, 0xf3, 0x55, 0xcf, 0xe7, 0x66, 0x7c, 0x23, 0x62,
	0xa4, 0x7f, 0x81, 0x5c, 0xa0, 0xd2, 0x02, 0x66, 0x42, 0xaa, 0x2a, 0x9f, 0x1d, 0xc9, 0xd3, 0x7b,
	0xe8, 0x37, 0xb6, 0x0f, 0xcd, 0x42, 0x0b, 0x0d, 0xbc, 0xa1, 0x67, 0xb2, 0xd0, 0x74, 0xa1, 0x19,
	0xd1, 0xff, 0xf0, 0x43, 0xf3, 0xa7, 0x89, 0x62, 0xd1, 0x9b, 0x04, 0x31, 0x18, 0xb4, 0x3f, 0x38,
	0xb2, 0x1f, 0xaf, 0xdd, 0xcf, 0x03, 0x90, 0x6b, 0x4c, 0xf8, 0x65, 0xb1, 0x69, 0xfd, 0x67, 0x24,
	0x26, 0xdc, 0x92, 0x54, 0x63, 0xab, 0x49, 0xb7, 0xd1, 0xa4, 0x75, 0xbd, 0xd7, 0x7c, 0xf1, 0x7f,
	0xa0, 0xdf, 0xb8, 0x63, 0xb7, 0x07, 0x3a, 0x85, 0xde, 0x24, 0x47, 0xa6, 0xd0, 0xc4, 0xb6, 0x3f,
	0x1e, 0xf2, 0x1b, 0x20, 0xc7, 0x08, 0xc5, 0x93, 0xf5, 0x7e, 0xac, 0x09, 0xbd, 0x03, 0x62, 0x93,
	0x1d, 0x59, 0xa7, 0xd3, 0xae, 0x73, 0x0a, 0xbd, 0x33, 0xce, 0xcb, 0x76, 0x8e, 0xd5, 0x7a, 0x0e,
	0xc4, 0x26, 0x3b, 0x44, 0xeb, 0x6b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x99, 0x4c, 0x4f, 0x10,
	0x05, 0x00, 0x00,
}
